# Build stage
FROM golang:1.24.4 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o proxy ./cmd/proxy

# Runtime stage
FROM scratch
COPY --from=builder /app/proxy /proxy
ENTRYPOINT ["/proxy"]
CMD ["--etcd=etcd:2379","--listen=:8080","--vnodes=100","--replicas=1"]
