# Build stage
FROM golang:1.24.4 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

# Runtime stage
FROM scratch
COPY --from=builder /app/server /server
ENTRYPOINT ["/server"]
CMD ["--port=50051","--wal=/data/wal.log"]
